import { createClientFromRequest } from "npm:@base44/sdk";
import { DEMO_ISSUES, DEMO_PRODUCT, DEMO_SLUG, DEMO_SUBMISSIONS, demoFixtureValid } from "../../shared/demo-fixture.ts";
import { error, errorMessage, json } from "../../shared/response.ts";

type Row=Record<string,any>;
const CHILDREN=["NotificationDelivery","ReporterMessage","DuplicateSuggestion","IssueReport","ActivityEvent","FeedbackAttachment","ReporterAccess","FeedbackSubmission","Issue"] as const;
async function clearDemo(sr:any,projectId:string){let removed=0;for(const name of CHILDREN){const entity=sr.entities[name];const rows=await entity.filter({project_id:projectId});for(const row of rows){await entity.delete(row.id);removed+=1;}}return removed;}
async function ensure(sr:any,name:string,filter:Row,value:Row){const entity=sr.entities[name];const existing=(await entity.filter(filter))[0];return existing??entity.create(value);}
async function seed(sr:any,project:Row,owner:string){const now="2026-07-27T12:00:00.000Z";const issueRows:Row[]=[];for(const issue of DEMO_ISSUES)issueRows.push(await ensure(sr,"Issue",{project_id:project.id,public_code:issue.public_code},{...issue,project_id:project.id,owner_id:owner,first_seen_at:now,last_seen_at:now,reproducibility:"confirmed",core_workflow_blocked:issue.public_code==="FI-DEMO01"}));const submissionRows:Row[]=[];for(const submission of DEMO_SUBMISSIONS)submissionRows.push(await ensure(sr,"FeedbackSubmission",{project_id:project.id,submission_key:submission.submission_key},{...submission,project_id:project.id,owner_id:owner,created_at:now,context_included:true}));for(let index=0;index<submissionRows.length;index++){const submission=submissionRows[index];const issue=index<3?issueRows[0]:issueRows[1];await ensure(sr,"IssueReport",{project_id:project.id,submission_id:submission.id},{project_id:project.id,owner_id:owner,issue_id:issue.id,submission_id:submission.id,similarity_score:index===2?.91:1,matching_reasons:index===2?["Mobile composer overlaps newest message"]:["Initial representative report"],grouping_method:index===2?"automatic":"manual_initial",review_status:"accepted",created_at:now});}await ensure(sr,"DuplicateSuggestion",{project_id:project.id,submission_id:submissionRows[3].id},{project_id:project.id,owner_id:owner,submission_id:submissionRows[3].id,source_issue_id:issueRows[1].id,candidate_issue_id:issueRows[0].id,similarity_score:.72,matching_reasons:["Both occur on older mobile devices"],conflicting_evidence:["Different product areas"],threshold_version:"demo-v1",status:"pending",created_at:now});await ensure(sr,"ReporterMessage",{project_id:project.id,idempotency_key:"demo-owner-request"},{project_id:project.id,owner_id:owner,submission_id:submissionRows[0].id,issue_id:issueRows[0].id,sender_type:"owner",message_type:"request_information",body:"Does this still happen after reopening the conversation?",visibility:"public",idempotency_key:"demo-owner-request",created_at:now});await ensure(sr,"ReporterMessage",{project_id:project.id,idempotency_key:"demo-reporter-reply"},{project_id:project.id,owner_id:owner,submission_id:submissionRows[0].id,issue_id:issueRows[0].id,sender_type:"reporter",message_type:"reporter_follow_up",body:"Yes. It happens again after reopening the conversation.",visibility:"public",idempotency_key:"demo-reporter-reply",created_at:now});await ensure(sr,"NotificationDelivery",{project_id:project.id,dedupe_key:"demo:failed:no-send"},{project_id:project.id,owner_id:owner,issue_id:issueRows[0].id,recipient_type:"owner",template_key:"owner_critical_issue",channel:"email",dedupe_key:"demo:failed:no-send",status:"failed",attempt_count:1,last_error_code:"demo_fixture",last_error_message:"Representative failed delivery; no provider call occurred.",payload:{productName:DEMO_PRODUCT},created_at:now,updated_at:now});return{issues:issueRows.length,submissions:submissionRows.length};}

Deno.serve(async(req)=>{try{if(req.method!=="POST")return error("Method not allowed",405);const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user?.email)return error("Authentication required",401);const input=await req.json();if(!["seed","reset","verify"].includes(input.action)||typeof input.projectId!=="string")return error("Invalid maintenance request",400);const sr=base44.asServiceRole;const project=await sr.entities.Project.get(input.projectId).catch(()=>null);if(!project||project.slug!==DEMO_SLUG||project.name!==DEMO_PRODUCT||(project.created_by??project.owner_id)!==user.email)return error("Demo project ownership check failed",403);if(!demoFixtureValid())return error("Demo fixture is invalid",500);if(input.action==="reset"){await clearDemo(sr,project.id);await seed(sr,project,user.email);}else if(input.action==="seed")await seed(sr,project,user.email);const issues=await sr.entities.Issue.filter({project_id:project.id});const submissions=await sr.entities.FeedbackSubmission.filter({project_id:project.id});const suggestions=await sr.entities.DuplicateSuggestion.filter({project_id:project.id});const valid=issues.length===2&&submissions.length===4&&suggestions.length===1;return json({success:true,valid,project:{name:project.name,slug:project.slug},counts:{issues:issues.length,submissions:submissions.length,suggestions:suggestions.length},deliveryEvidence:"No email delivery is claimed by this fixture."});}catch(err){return error(errorMessage(err),500);}});
