import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('landing CTA, metadata, responsive layout, and axe smoke',async({page})=>{await page.goto('/');await expect(page.getByRole('link',{name:/create|get started|start/i}).first()).toBeVisible();await expect(page).toHaveTitle(/Feedback Inbox/);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow).toBe(false);await page.waitForTimeout(1100);const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(item=>['critical','serious'].includes(item.impact??''))).toEqual([]);});
test('representative demo is honestly labeled',async({page})=>{await page.goto('/demo');await expect(page.getByText('Representative demo state').first()).toBeVisible();await expect(page.getByText('Live product behavior',{exact:true})).toBeVisible();await expect(page.getByText(/no email delivery/i)).toBeVisible();});
test('preview exposes an installable manifest and registers a service worker',async({page,context})=>{await page.goto('/');const manifestHref=await page.locator('link[rel="manifest"]').getAttribute('href');expect(manifestHref).toBeTruthy();const manifest=await (await context.request.get(manifestHref!)).json();expect(manifest).toMatchObject({name:'Feedback Inbox',short_name:'Feedback',display:'standalone',start_url:'/',scope:'/'});await expect.poll(()=>page.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration()))).toBe(true);});
test('owner route guards unauthenticated visitors without fabricating a session',async({page})=>{await page.goto('/app/issues');await expect(page.getByText(/sign in|log in|welcome/i).first()).toBeVisible({timeout:15_000});});
test('public draft restores, blocks offline submission, and submits deliberately after reconnect',async({page,context})=>{await page.route('**/apps/*/functions/**',async route=>{const name=new URL(route.request().url()).pathname.split('/').at(-1);if(name==='get-public-project')return route.fulfill({json:{slug:'trailverse-demo',name:'TrailVerse Demo',description:'Demo project',allowAnonymous:true,feedbackTypesEnabled:['bug','feature','general'],collectReporterEmail:true,isActive:true}});if(name==='submit-feedback')return route.fulfill({json:{success:true,duplicate:false,submissionRef:'submission-1',trackingUrl:'/track/demo-token',publicCode:'FI-DEMO01'}});return route.fulfill({json:{success:true}});});await page.goto('/f/trailverse-demo');await page.getByRole('button',{name:/report a problem/i}).click();await page.getByLabel('Describe the problem').fill('The mobile composer covers the latest message.');await page.waitForTimeout(600);await page.reload();await expect(page.getByText('Your unfinished feedback was restored.')).toBeVisible();await expect(page.getByLabel('Describe the problem')).toHaveValue('The mobile composer covers the latest message.');await context.setOffline(true);await page.evaluate(()=>window.dispatchEvent(new Event('offline')));await expect(page.getByRole('button',{name:/send feedback/i})).toBeDisabled();await expect(page.getByText(/draft is saved on this device/i)).toBeVisible();await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await expect(page.getByRole('button',{name:/send feedback/i})).toBeEnabled({timeout:5_000});await page.getByRole('button',{name:/send feedback/i}).click();await expect(page.getByRole('heading',{name:'Your feedback is in'})).toBeVisible();});
test('public attachment validation rejects unsafe files before upload',async({page})=>{await page.route('**/apps/*/functions/get-public-project',route=>route.fulfill({json:{slug:'trailverse-demo',name:'TrailVerse Demo',allowAnonymous:true,feedbackTypesEnabled:['bug'],collectReporterEmail:true,isActive:true}}));await page.goto('/f/trailverse-demo');await page.getByRole('button',{name:/report a problem/i}).click();await page.locator('input[type=file]').setInputFiles({name:'unsafe.txt',mimeType:'text/plain',buffer:Buffer.from('not an image')});await expect(page.getByText(/Only PNG, JPEG, and WebP/i)).toBeVisible();});
test('tracking invalid token shows a designed state',async({page})=>{await page.route('**/apps/*/functions/access-tracking-page',route=>route.fulfill({status:404,json:{error:'Invalid or expired tracking link'}}));await page.goto('/track/invalid-token');await expect(page.getByRole('heading',{name:/not available|invalid|expired/i})).toBeVisible();});
test('authenticated owner issue list integration requires explicit credentials',async()=>{test.skip(!process.env.BASE44_E2E_OWNER_EMAIL,'Skipped: authenticated owner credentials/local session are not configured; no session is fabricated.');});
