import { Link } from 'react-router-dom';
import { ArrowRight, Bug, Check, MessageSquareText, ScanSearch } from 'lucide-react';
import { Brand, BrandMark } from '@/components/Brand';

const reports = [
  ['BUG REPORT', 'Checkout freezes after I add a coupon.'],
  ['GENERAL', 'The discount box stopped responding on mobile.'],
  ['BUG REPORT', 'Apply code does nothing in Safari.'],
];

export function LandingPage() {
  return <div className="min-h-screen overflow-hidden bg-canvas">
    <header className="border-b border-line"><div className="fi-container flex h-16 items-center justify-between"><Brand /><nav className="flex items-center gap-2"><a href="#how" className="hidden min-h-11 items-center px-3 text-sm text-ink-muted hover:text-ink sm:inline-flex">How it works</a><Link to="/app" className="inline-flex min-h-11 items-center rounded-md border border-ink bg-ink px-4 text-sm font-medium text-white">Open workspace</Link></nav></div></header>
    <main>
      <section className="fi-container grid min-h-[700px] items-center gap-12 py-20 lg:grid-cols-[1.04fr_.96fr] lg:py-24">
        <div className="max-w-3xl"><p className="fi-eyebrow">Feedback intelligence for product teams.</p><h1 className="fi-display mt-5 text-[clamp(3rem,6.3vw,5.2rem)] font-semibold leading-[.94] tracking-[-.065em]">Feedback should tell you<br className="hidden sm:block" /> what to fix next.</h1><p className="mt-7 max-w-xl text-[17px] leading-7 text-ink-muted">Collect reports through one simple link. VensaOS groups repeated problems, preserves the evidence, and helps teams understand what is affecting users most.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/app/setup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-ink px-5 text-sm font-medium text-white">Create your feedback board <ArrowRight className="h-4 w-4" /></Link><Link to="/demo" className="inline-flex min-h-12 items-center justify-center rounded-md border border-line-strong bg-surface px-5 text-sm font-medium text-ink">View the demo</Link></div><p className="fi-mono mt-5 text-[10px] uppercase tracking-[.1em] text-ink-faint">Turn scattered feedback into clear product decisions.</p></div>
        <ConvergenceVisual />
      </section>

      <section className="border-y border-line bg-surface"><div className="fi-container"><div className="border-b border-line py-12"><p className="fi-eyebrow">The product loop</p><h2 className="fi-display mt-4 text-3xl font-medium leading-tight">Raw language becomes a clear issue—without losing the source.</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-6">{[['01','Collect','Share one focused link.'],['02','Understand','Keep the original evidence readable.'],['03','Group','Connect repeated signals.'],['04','Prioritize','See what affects users most.'],['05','Resolve','Record what changed.'],['06','Close the loop','Update the people who reported it.']].map(([n,t,d]) => <div key={n} className="border-b border-line p-6 last:border-b-0 sm:border-r lg:border-b-0 lg:last:border-r-0"><span className="fi-mono text-[11px] text-ink-faint">{n}</span><h3 className="fi-display mt-8 text-xl font-medium">{t}</h3><p className="mt-2 text-sm leading-6 text-ink-muted">{d}</p></div>)}</div></div></section>

      <section id="how" className="fi-container py-24"><div className="grid items-start gap-12 lg:grid-cols-2"><div className="lg:sticky lg:top-12"><p className="fi-eyebrow">Evidence first</p><h2 className="fi-display mt-4 max-w-lg text-4xl font-medium leading-[1.05]">The answer stays connected to the words that led there.</h2><p className="mt-5 max-w-md text-[15px] leading-7 text-ink-muted">Normalized issues are useful only when the original evidence remains readable. Every finding keeps its source report, environment, and activity close at hand.</p></div><div className="border-y border-line bg-surface"><div className="flex items-center justify-between border-b border-line px-6 py-4"><div><p className="fi-mono text-[10px] text-ink-faint">FI-7K2M9A</p><p className="mt-1 font-medium">Coupon action freezes checkout</p></div><span className="fi-mono rounded bg-warning-soft px-2 py-1 text-[10px] text-warning">HIGH</span></div><div className="p-6"><p className="fi-eyebrow">Original evidence</p><blockquote className="mt-4 border-l-2 border-critical pl-4 text-lg leading-7">“Apply code does nothing in Safari. I had to restart checkout.”</blockquote><div className="mt-8 grid grid-cols-3 border-y border-line py-4"><Metric value="3" label="Reports" /><Metric value="3" label="Affected" /><Metric value="Today" label="Last seen" /></div><div className="mt-6 flex items-center gap-3 text-sm text-ink-muted"><ScanSearch className="h-4 w-4" /> Source evidence remains attached to the issue.</div></div></div></div></section>

      <section className="border-y border-line bg-surface-subtle"><div className="fi-container grid items-center gap-16 py-24 lg:grid-cols-[1fr_.9fr]"><div className="max-w-lg"><p className="fi-eyebrow">Simple on purpose</p><h2 className="fi-display mt-4 text-4xl font-medium leading-tight">A feedback form people will actually finish.</h2><p className="mt-5 text-[15px] leading-7 text-ink-muted">Reporters choose what they want to share, answer only relevant questions, and receive a private link to follow the result.</p><ul className="mt-7 space-y-3 text-sm">{['No account required','Clear, progressive questions','Private status tracking'].map(x => <li key={x} className="flex items-center gap-3"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-ink text-white"><Check className="h-3 w-3" /></span>{x}</li>)}</ul></div><div className="mx-auto w-full max-w-md rounded-xl border border-line bg-surface p-6 shadow-sheet"><div className="flex items-center gap-3 border-b border-line pb-5"><BrandMark className="h-9 w-9" /><div><p className="font-medium">Share feedback</p><p className="text-xs text-ink-faint">Usually less than a minute</p></div></div><div className="mt-5 space-y-3"><PreviewChoice icon={<Bug />} title="Report a problem" /><PreviewChoice icon={<MessageSquareText />} title="Suggest an improvement" /><PreviewChoice icon={<MessageSquareText />} title="Share general feedback" /></div></div></div></section>

      <section className="fi-container py-24 text-center"><BrandMark className="mx-auto h-11 w-11" /><h2 className="fi-display mx-auto mt-6 max-w-2xl text-4xl font-medium leading-tight">Turn the next report into something your team can act on.</h2><Link to="/app/setup" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-md bg-ink px-5 text-sm font-medium text-white">Create a feedback board <ArrowRight className="h-4 w-4" /></Link></section>
    </main>
    <footer className="border-t border-line"><div className="fi-container flex flex-col gap-4 py-7 text-sm text-ink-muted sm:flex-row sm:items-center sm:justify-between"><Brand /><p>Built for clear product decisions.</p></div></footer>
  </div>;
}

function ConvergenceVisual() { return <div className="relative min-h-[500px] rounded-xl border border-line bg-surface p-5 sm:p-8"><div className="absolute inset-y-0 left-[58%] border-l border-dashed border-line-strong" /><p className="fi-eyebrow">Incoming reports</p><div className="relative mt-12 grid grid-cols-[1fr_.88fr] gap-5 sm:gap-8"><div className="space-y-4">{reports.map(([type,body]) => <div key={body} className="report-slip rounded-lg border border-line bg-canvas p-4"><p className="fi-mono text-[9px] text-ink-faint">{type}</p><p className="mt-3 text-sm leading-5">{body}</p></div>)}</div><div className="issue-result self-center rounded-lg border border-ink bg-ink p-5 text-white"><p className="fi-mono text-[9px] text-white/55">GROUPED ISSUE</p><p className="fi-display mt-3 text-xl font-medium leading-tight">Coupon action freezes checkout</p><div className="mt-8 border-t border-white/20 pt-4"><p className="fi-mono text-[9px] text-white/55">3 REPORTS · 3 AFFECTED</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/20"><div className="h-full w-4/5 bg-critical" /></div><p className="fi-mono mt-2 text-[9px] text-white/55">HIGH ATTENTION</p></div></div></div><div className="absolute bottom-5 left-5 right-5 flex justify-between sm:bottom-8 sm:left-8 sm:right-8"><span className="fi-mono text-[9px] text-ink-faint">SOURCE PRESERVED</span><span className="fi-mono text-[9px] text-ink-faint">ISSUE FI-7K2M9A</span></div></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div><p className="fi-display text-lg font-medium">{value}</p><p className="fi-mono mt-1 text-[9px] uppercase text-ink-faint">{label}</p></div>; }
function PreviewChoice({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex min-h-14 items-center gap-3 rounded-lg border border-line px-4 text-sm"><span className="text-ink-muted [&>svg]:h-4 [&>svg]:w-4">{icon}</span><span>{title}</span><ArrowRight className="ml-auto h-4 w-4 text-ink-faint" /></div>; }
