import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Clock3, Image, Monitor, Quote, UserRound } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getActivityForIssue, getIssue, getReportsForIssue, getSubmission, resolveIssue } from '@/lib/api';
import { formatTime, severityLabel, statusLabel, typeLabel } from '@/lib/format';
import { Button, EmptyState, InlineError, SeverityBadge, Skeleton, StatusBadge, Textarea } from '@/components/ui';

const RESOLVABLE = new Set(['open','unreviewed','needs_info','planned','in_progress','testing','reopened']);
export function OwnerIssueDetailPage() {
  const { issueId = '' } = useParams(); const queryClient = useQueryClient(); const [note,setNote] = useState(''); const [resolveError,setResolveError] = useState<string|null>(null);
  const issueQuery = useQuery({ queryKey:['issue',issueId], queryFn:()=>getIssue(issueId) });
  const reportQuery = useQuery({ queryKey:['issue-report',issueId], queryFn:async()=>{ const links=await getReportsForIssue(issueId); return Promise.all(links.filter(link=>link.review_status!=='rejected').map(async link=>({link,submission:await getSubmission(link.submission_id)}))); } });
  const activityQuery = useQuery({ queryKey:['activity',issueId], queryFn:()=>getActivityForIssue(issueId) });
  const mutation = useMutation({ mutationFn:()=>resolveIssue(issueId,note.trim()), onSuccess:async()=>{ setNote(''); await Promise.all([queryClient.invalidateQueries({queryKey:['issue',issueId]}),queryClient.invalidateQueries({queryKey:['activity',issueId]}),queryClient.invalidateQueries({queryKey:['issues']})]); }, onError:()=>setResolveError('The issue could not be resolved. Check your connection and try again.') });
  if (issueQuery.isLoading) return <div className="mx-auto max-w-[1180px] space-y-5 px-4 py-10 sm:px-7"><Skeleton className="h-8 w-32"/><Skeleton className="h-32"/><Skeleton className="h-96"/></div>;
  if (issueQuery.isError || !issueQuery.data) return <div className="mx-auto max-w-[1180px] px-4 py-10"><EmptyState title="Issue not found" description="This issue may have been removed or does not belong to your project." icon={<Quote className="h-5 w-5" />} action={<Link to="/app/issues"><Button variant="secondary">Back to issues</Button></Link>} /></div>;
  const issue=issueQuery.data as typeof issueQuery.data & { priority_explanation?: string[] }; const reports=reportQuery.data ?? []; const report=reports[0]?.submission; const canResolve=RESOLVABLE.has(issue.status);
  return <div className="mx-auto max-w-[1240px] px-4 py-6 sm:px-7 md:py-8"><Link to="/app/issues" className="inline-flex min-h-11 items-center gap-2 text-sm text-ink-muted hover:text-ink"><ArrowLeft className="h-4 w-4"/>All issues</Link>
    <header className="border-b border-line pb-8 pt-3"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div className="max-w-3xl"><div className="flex flex-wrap items-center gap-3"><span className="fi-mono text-[10px] text-ink-faint">{issue.public_code}</span><SeverityBadge severity={issue.severity ?? 'medium'} label={severityLabel(issue.severity)} /><StatusBadge status={issue.status} label={statusLabel(issue.status)} /></div><h1 className="fi-display mt-4 text-3xl font-medium leading-[1.08] sm:text-[42px]">{issue.title}</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-ink-muted">{issue.description || 'A normalized issue created from the original report below.'}</p></div><div className="grid shrink-0 grid-cols-2 gap-x-8 gap-y-4 border-l border-line pl-6"><Metric value={String(issue.report_count ?? 0)} label="Reports"/><Metric value={String(issue.affected_user_count ?? 0)} label="Affected"/><Metric value={String(Math.round(issue.priority_score ?? 0))} label="Priority"/><Metric value={formatTime(issue.last_seen_at)} label="Last seen"/></div></div></header>
    <div className="grid gap-12 py-10 lg:grid-cols-[minmax(0,1fr)_360px]"><main className="space-y-12"><Section eyebrow="Source evidence" title={`${reports.length || ''} user report${reports.length === 1 ? '' : 's'}`}><div className="border-t border-line">{reportQuery.isLoading ? <Skeleton className="h-28"/> : reports.length ? reports.map(({link,submission:item})=><div key={item.id} className="border-b border-line bg-surface px-5 py-6 sm:px-7"><div className="flex items-center justify-between"><span className="fi-mono text-[10px] uppercase text-ink-faint">{typeLabel(item.type)} · {link.grouping_method?.replace('_',' ')}</span><span className="fi-mono text-[10px] text-ink-faint">{formatTime(item.created_at ?? item.created_date)}</span></div><blockquote className="mt-6 border-l-2 border-critical pl-5 text-lg leading-8">{item.description}</blockquote>{item.expected_behavior && <div className="mt-5 border-t border-line pt-4"><p className="fi-eyebrow">Expected behavior</p><p className="mt-2 text-sm leading-6 text-ink-muted">{item.expected_behavior}</p></div>}{link.matching_reasons?.length ? <div className="mt-5 rounded-md bg-surface-subtle p-4"><p className="fi-eyebrow">Why grouped · {Math.round((link.similarity_score ?? 0)*100)}%</p><ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-ink-muted">{link.matching_reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>:null}</div>) : <p className="border-b border-line py-6 text-sm text-ink-muted">No linked source report was found.</p>}</div></Section>
      <Section eyebrow="Captured context" title="Environment"><div className="grid border-y border-line sm:grid-cols-2"><Context icon={<Monitor/>} label="Page" value={report?.page_url || 'Not provided'} /><Context icon={<UserRound/>} label="Reporter" value={report?.reporter_email ? 'Known reporter' : 'Anonymous'} /></div><p className="mt-3 text-xs text-ink-faint">Browser and device context will appear here when collection is enabled in the next stage.</p></Section>
      <Section eyebrow="Attachments" title="Evidence"><EmptyState icon={<Image className="h-5 w-5" />} title="No screenshot evidence" description="Screenshot capture is intentionally not active in this stage. Uploaded evidence will appear here without changing the source report." /></Section>
    </main><aside className="space-y-10">{issue.priority_explanation?.length ? <section><h2 className="fi-display text-xl font-medium">Why this priority</h2><p className="mt-2 text-sm text-ink-muted">Deterministic score: {Math.round(issue.priority_score ?? 0)}</p><ul className="mt-4 space-y-2 text-xs text-ink-muted">{issue.priority_explanation.map(item=><li key={item} className="border-b border-line pb-2">{item}</li>)}</ul></section>:null}<section><h2 className="fi-display text-xl font-medium">Activity</h2><div className="mt-5 border-l border-line pl-6">{activityQuery.data?.length ? activityQuery.data.map(event => <div key={event.id} className="relative pb-7 last:pb-0"><span className="absolute -left-[31px] top-0 flex h-4 w-4 items-center justify-center rounded-full border border-line bg-canvas"><span className="h-1.5 w-1.5 rounded-full bg-ink-muted"/></span><p className="text-sm leading-6">{event.public_message ?? event.internal_message ?? event.event_type}</p><p className="fi-mono mt-1 text-[9px] uppercase text-ink-faint">{formatTime(event.created_at ?? event.created_date)}</p></div>) : <div className="flex gap-3 text-sm text-ink-muted"><Clock3 className="h-4 w-4"/>No activity yet.</div>}</div></section>
      <section className="border-t border-line pt-8"><h2 className="fi-display text-xl font-medium">Resolution</h2>{issue.status === 'resolved' ? <div className="mt-4 rounded-lg border border-success/25 bg-success-soft p-5"><div className="flex items-center gap-2 text-sm font-medium text-success"><CheckCircle2 className="h-4 w-4"/>Resolved</div><p className="mt-3 text-sm leading-6">{issue.public_resolution_note}</p><p className="fi-mono mt-3 text-[9px] text-ink-faint">{formatTime(issue.resolved_at)}</p></div> : canResolve ? <form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();setResolveError(null);mutation.mutate();}}><label htmlFor="resolution-note" className="text-sm text-ink-muted">Explain the outcome to reporters</label><Textarea id="resolution-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="What changed, and what should reporters expect now?" required />{resolveError && <InlineError>{resolveError}</InlineError>}<Button className="w-full" type="submit" disabled={mutation.isPending || !note.trim()}>{mutation.isPending ? 'Resolving…' : 'Resolve with public note'}</Button></form> : <p className="mt-3 text-sm text-ink-muted">This issue cannot be resolved from its current status.</p>}</section></aside></div>
  </div>;
}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}) { return <section><p className="fi-eyebrow">{eyebrow}</p><h2 className="fi-display mt-2 mb-5 text-2xl font-medium">{title}</h2>{children}</section>; }
function Metric({value,label}:{value:string;label:string}) { return <div><p className="fi-display text-xl font-medium">{value}</p><p className="fi-mono mt-1 text-[9px] uppercase text-ink-faint">{label}</p></div>; }
function Context({icon,label,value}:{icon:React.ReactNode;label:string;value:string}) { return <div className="flex gap-3 border-b border-line p-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><span className="text-ink-faint [&>svg]:h-4 [&>svg]:w-4">{icon}</span><div className="min-w-0"><p className="fi-mono text-[9px] uppercase text-ink-faint">{label}</p><p className="mt-2 break-all text-sm text-ink-muted">{value}</p></div></div>; }
