import { useCallback } from 'react';
import { useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { CheckCircle2, Clock3, Link2Off, LockKeyhole, Monitor } from 'lucide-react';
import { accessTrackingPage, apiErrorMessage, getReporterAttachmentAccess } from '@/lib/api';
import { formatTime, statusLabel, typeLabel } from '@/lib/format';
import { Brand, BrandMark } from '@/components/Brand';
import { AttachmentGallery, type GalleryAttachment } from '@/components/AttachmentGallery';
import { Skeleton, StatusBadge } from '@/components/ui';

export function TrackingPage(){
 const {token=''}=useParams();
 const {data,isLoading,error}=useQuery({queryKey:['tracking',token],queryFn:()=>accessTrackingPage(token),retry:false});
 const access=useCallback((attachment:GalleryAttachment)=>getReporterAttachmentAccess(token,attachment.accessKey??''),[token]);
 if(isLoading)return <Frame><Skeleton className="h-8 w-40"/><Skeleton className="mt-8 h-40"/><Skeleton className="mt-6 h-60"/></Frame>;
 if(error||!data){const message=apiErrorMessage(error);const expired=/expir/i.test(message);return <Frame><div className="py-20 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-lg border border-line bg-surface text-ink-muted">{expired?<Clock3 className="h-5 w-5"/>:<Link2Off className="h-5 w-5"/>}</span><h1 className="fi-display mt-6 text-3xl font-medium">{expired?'This tracking link has expired':'This tracking link is not valid'}</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-ink-muted">{expired?'The private access window has ended. Contact the product team if you still need an update.':'Check that the entire private link was copied. Tracking links cannot be searched or recovered publicly.'}</p></div></Frame>}
 return <Frame><header className="border-b border-line pb-8"><div className="flex flex-wrap items-center gap-3">{data.publicCode&&<span className="fi-mono text-[10px] text-ink-faint">{data.publicCode}</span>}<StatusBadge status={data.status} label={statusLabel(data.status)}/></div><h1 className="fi-display mt-4 text-4xl font-medium leading-tight">{data.issueTitle??'Your report'}</h1><p className="mt-3 flex items-center gap-2 text-xs text-ink-faint"><LockKeyhole className="h-3.5 w-3.5"/>Only someone with this private link can view this report and its evidence.</p></header><div className="grid gap-12 py-10 lg:grid-cols-[1fr_300px]"><main className="space-y-10"><section><p className="fi-eyebrow">Original report</p><blockquote className="mt-4 border-y border-line bg-surface px-6 py-7 text-lg leading-8">{data.originalDescription}</blockquote><p className="fi-mono mt-3 text-[9px] uppercase text-ink-faint">{typeLabel(data.reportType)} · {formatTime(data.submittedAt)}</p></section>
   <section><p className="fi-eyebrow">Your screenshots</p><h2 className="fi-display mb-4 mt-2 text-2xl font-medium">Private evidence</h2><AttachmentGallery attachments={data.attachments} getAccess={access}/></section>
   <section><p className="fi-eyebrow">Submitted context</p><h2 className="fi-display mb-4 mt-2 text-2xl font-medium">Environment</h2>{data.context?<div className="grid gap-px bg-line sm:grid-cols-2"><Context label="Browser" value={[data.context.browserName,data.context.browserVersion].filter(Boolean).join(' ')}/><Context label="Device" value={[data.context.deviceType,data.context.operatingSystem].filter(Boolean).join(' · ')}/><Context label="Screen" value={size(data.context.screenWidth,data.context.screenHeight)}/><Context label="Viewport" value={size(data.context.viewportWidth,data.context.viewportHeight)}/><Context label="Page" value={data.context.pageUrl??'Not submitted'} wide/></div>:<div className="rounded-lg border border-dashed border-line p-6 text-center"><Monitor className="mx-auto h-5 w-5 text-ink-faint"/><p className="mt-2 text-sm">Context was removed before submission</p></div>}</section>
   {data.publicResolutionNote&&<section className="rounded-lg border border-success/25 bg-success-soft p-6"><p className="flex items-center gap-2 text-sm font-medium text-success"><CheckCircle2 className="h-4 w-4"/>Resolution note</p><p className="mt-3 text-[15px] leading-7">{data.publicResolutionNote}</p></section>}
  </main><aside><h2 className="fi-display text-xl font-medium">Public activity</h2><div className="mt-5 border-l border-line pl-6">{data.activity.length?data.activity.map((event,i)=><div key={`${event.createdAt}-${i}`} className="relative pb-7 last:pb-0"><span className="absolute -left-[31px] top-0 h-4 w-4 rounded-full border-4 border-canvas bg-ink-muted"/><p className="text-sm leading-6">{event.message}</p><p className="fi-mono mt-1 text-[9px] text-ink-faint">{formatTime(event.createdAt)}</p></div>):<p className="text-sm leading-6 text-ink-muted">The team has your report. Public updates will appear here.</p>}</div></aside></div></Frame>
}
function size(width:number|null,height:number|null){return width&&height?`${width} × ${height}`:'Not submitted';}
function Context({label,value,wide}:{label:string;value:string;wide?:boolean}){return <div className={`bg-surface p-4 ${wide?'sm:col-span-2':''}`}><p className="fi-mono text-[9px] uppercase text-ink-faint">{label}</p><p className="mt-2 break-all text-sm text-ink-muted">{value||'Not submitted'}</p></div>;}
function Frame({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-canvas"><header className="border-b border-line"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><Brand/><BrandMark className="hidden h-5 w-5 opacity-60 sm:block"/></div></header><main className="mx-auto max-w-4xl px-4 py-10 sm:px-6 sm:py-16">{children}</main></div>}
